### ISSUE TITLE
Import LocoKit in Objective-C

### ISSUE THREAD

**Issue by WesselKoorn** [sobri909/LocoKit#58]
Hello, I've very little experience with iOS development so maybe this is an obvious question. I try to import LocoKit into my project written in Objective-C. I've installed LocoKit using Pods. When I try to use the `TimelineManager` (or every other class) I get the following error: `Unknown type name 'TimelineManager'`. I can instantiate the `LocomotionManager` class but I can't call any properties of it like `startRecording()`. This are my import statements in the header file:

```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import "LocoKit-Swift.h"
#import <LocoKit/LocoKit-Swift.h>
```

Any idea how to fix this?

Thanks!

**Comment by sobri909** [comment]
Hi @WesselKoorn! 

The first step I'd recommend is switching to the `develop` branch, as the current master branch is very out of date. 

```ruby
pod 'LocoKit', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'develop'
pod 'LocoKit/Timelines', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'develop'
pod 'LocoKitCore', :git => 'https://github.com/sobri909/LocoKit.git', :branch => 'develop'
```

Then have a look at the code in the develop branch's Demo App, to see the API changes. `TimelineManager` has been replaced by `TimelineRecorder` (although is otherwise almost identical). 

Then after that you'll probably need to write a Swift file that wraps the parts of LocoKit that you want to use, because most (all?) of LocoKit's classes are no longer exposed as `@objc` classes.

So what you'd do is write a single Swift file / class, that you use to talking to / controlling LocoKit, then expose that Swift class as @objc, so that you can use it from within your Objective-C code.

Although it may be possible now to use Swift code directly with React Native, rather than having to do the bridging via Objective-C. It would be worth looking into that, as it will reduce the complexity of your integration quite a bit.
